# Generated by Django 4.0.6 on 2022-08-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_football_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classicgame',
            name='game_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='classicgame',
            unique_together={('user', 'game_id')},
        ),
        migrations.RemoveField(
            model_name='classicgame',
            name='away_team_score',
        ),
        migrations.RemoveField(
            model_name='classicgame',
            name='home_team_score',
        ),
        migrations.RemoveField(
            model_name='classicgame',
            name='stadium_name',
        ),
        migrations.RemoveField(
            model_name='classicgame',
            name='weather_at_kickoff',
        ),
        migrations.RemoveField(
            model_name='classicgame',
            name='winning_team',
        ),
    ]
