# Generated by Django 4.0.6 on 2022-08-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_football_app', '0002_classicgame_game_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classicgame',
            name='year',
            field=models.CharField(default=0, max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classicgame',
            name='game_id',
            field=models.CharField(max_length=25),
        ),
    ]
