# Generated by Django 4.0.6 on 2022-08-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_football_app', '0003_classicgame_year_alter_classicgame_game_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='classicgame',
            name='away_team_score',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classicgame',
            name='home_team_score',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classicgame',
            name='week',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
